INSERT INTO tutees VALUES ('E3068780', 'Taryn Galbreath', 'Chinese Language');
INSERT INTO tutees VALUES ('E6304277', 'Susie Bompass', 'Chinese Studies');
INSERT INTO tutees VALUES ('E4713577', 'Babs Pencost', ' Communications and New Media');
INSERT INTO tutees VALUES ('E6034599', 'Elisabetta Yaxley', 'Economics');
INSERT INTO tutees VALUES ('E6603588', 'Pippa Rylatt', 'English Language');
INSERT INTO tutees VALUES ('E2686258', 'Lyndsay Streeter', 'English Literature');
INSERT INTO tutees VALUES ('E0473646', 'Em Willmett', 'Geography');
INSERT INTO tutees VALUES ('E9319832', 'Charis Presnell', 'Global Studies');
INSERT INTO tutees VALUES ('E4257842', 'Lindy Akett', 'History ');
INSERT INTO tutees VALUES ('E6111296', 'Rivkah Sotheby', 'Japanese Studies');
INSERT INTO tutees VALUES ('E3538413', 'Bat Bannell', 'Malay Studies');
INSERT INTO tutees VALUES ('E7903311', 'Ebony Malec', 'Philosophy');
INSERT INTO tutees VALUES ('E0479650', 'Reyna Nibley', ' Political Science');
INSERT INTO tutees VALUES ('E3232950', 'Reid Giraldon', ' Psychology');
INSERT INTO tutees VALUES ('E7465636', 'Kimberlee Gerin', ' Social Work');
INSERT INTO tutees VALUES ('E0701254', 'Milli Cavey', ' Sociology');
INSERT INTO tutees VALUES ('E5570939', 'Morley Jorez', ' South Asian Studies');
INSERT INTO tutees VALUES ('E9322136', 'Rockey O''''Neill', ' Southeast Asian Studies');
INSERT INTO tutees VALUES ('E2020108', 'Meredith Oleszczak', 'Theatre Studies');
INSERT INTO tutees VALUES ('E9745255', 'Tome Diplock', ' Chemistry');
INSERT INTO tutees VALUES ('E6704382', 'Jaquenetta Kubu', 'Data Science and Analytics');
INSERT INTO tutees VALUES ('E7319058', 'Maggy Boshers', 'Life Sciences');
INSERT INTO tutees VALUES ('E8676741', 'Ollie Ffoulkes', 'Mathematics');
INSERT INTO tutees VALUES ('E1414962', 'Rivkah Skace', 'Physics');
INSERT INTO tutees VALUES ('E4373271', 'Inga D''''Avaux', 'Quantitative Finance');
INSERT INTO tutees VALUES ('E9198905', 'Ardisj Maving', 'Statistics');
INSERT INTO tutees VALUES ('E8395214', 'Hortense Ivermee', 'Chinese Language');
INSERT INTO tutees VALUES ('E0883821', 'Abran Elven', 'Chinese Studies');
INSERT INTO tutees VALUES ('E1159605', 'Arthur Boyland', ' Communications and New Media');
INSERT INTO tutees VALUES ('E3544945', 'Sibylle Boden', 'Economics');
INSERT INTO tutees VALUES ('E5413410', 'Harry Melhuish', 'English Language');
INSERT INTO tutees VALUES ('E4214943', 'Brandi Duns', 'English Literature');
INSERT INTO tutees VALUES ('E5345541', 'Drusie Bridgeman', 'Geography');
INSERT INTO tutees VALUES ('E7270585', 'Florie Moncreif', 'Global Studies');
INSERT INTO tutees VALUES ('E1220276', 'Floyd Dempster', 'History ');
INSERT INTO tutees VALUES ('E4507057', 'Torrence Florentine', 'Japanese Studies');
INSERT INTO tutees VALUES ('E1509200', 'Roxie Asquith', 'Malay Studies');
INSERT INTO tutees VALUES ('E0207150', 'Salvador Baldam', 'Philosophy');
INSERT INTO tutees VALUES ('E4670119', 'Myra Ballendine', ' Political Science');
INSERT INTO tutees VALUES ('E8555198', 'Susanetta Pleasance', ' Psychology');
INSERT INTO tutees VALUES ('E1502151', 'Rosamond Brunke', ' Social Work');
INSERT INTO tutees VALUES ('E0734372', 'Madelaine Gilliver', ' Sociology');
INSERT INTO tutees VALUES ('E6413081', 'Egbert Tavinor', ' South Asian Studies');
INSERT INTO tutees VALUES ('E5259906', 'Calhoun Cumberledge', ' Southeast Asian Studies');
INSERT INTO tutees VALUES ('E0857199', 'Lorinda Avrahamian', 'Theatre Studies');
INSERT INTO tutees VALUES ('E7879446', 'Berton Eldon', ' Chemistry');
INSERT INTO tutees VALUES ('E3337941', 'Ricoriki Havick', 'Data Science and Analytics');
INSERT INTO tutees VALUES ('E8910134', 'Hasheem Dalgardno', 'Life Sciences');
INSERT INTO tutees VALUES ('E6850402', 'Maureene Creffeild', 'Mathematics');
INSERT INTO tutees VALUES ('E9931444', 'Edd McCritichie', 'Physics');
INSERT INTO tutees VALUES ('E3507474', 'Jarrad Prosch', 'Quantitative Finance');
INSERT INTO tutees VALUES ('E9685768', 'Lester Ducroe', 'Statistics');
INSERT INTO tutees VALUES ('E3485510', 'Meggi Sinnocke', 'Chinese Language');
INSERT INTO tutees VALUES ('E0994897', 'Auroora Adelsberg', 'Chinese Studies');
INSERT INTO tutees VALUES ('E5836478', 'Hershel Antonovic', ' Communications and New Media');
INSERT INTO tutees VALUES ('E8367366', 'Gennifer Tillyer', 'Economics');
INSERT INTO tutees VALUES ('E6073249', 'Purcell Huggett', 'English Language');
INSERT INTO tutees VALUES ('E7916869', 'Reena Bris', 'English Literature');
INSERT INTO tutees VALUES ('E6546187', 'Barron Roath', 'Geography');
INSERT INTO tutees VALUES ('E7831349', 'Georgie Dyka', 'Global Studies');
INSERT INTO tutees VALUES ('E1336941', 'Anatola Enbury', 'History ');
INSERT INTO tutees VALUES ('E4363914', 'Neddie Abys', 'Japanese Studies');
INSERT INTO tutees VALUES ('E6081863', 'Avril Cosser', 'Malay Studies');
INSERT INTO tutees VALUES ('E7139252', 'Sibeal Schimmang', 'Philosophy');
INSERT INTO tutees VALUES ('E3629296', 'Rosabelle Durbann', ' Political Science');
INSERT INTO tutees VALUES ('E8707272', 'Arri O''''Lennane', ' Psychology');
INSERT INTO tutees VALUES ('E4723677', 'Gregoire Corsor', ' Social Work');
INSERT INTO tutees VALUES ('E5850137', 'Shirley Watford', ' Sociology');
INSERT INTO tutees VALUES ('E8053809', 'Patrice Olivazzi', ' South Asian Studies');
INSERT INTO tutees VALUES ('E9685698', 'Richy Leeke', ' Southeast Asian Studies');
INSERT INTO tutees VALUES ('E4200410', 'Rurik Butcher', 'Theatre Studies');
INSERT INTO tutees VALUES ('E4312763', 'Harlin Niece', ' Chemistry');
INSERT INTO tutees VALUES ('E5790668', 'Rocky Stoeck', 'Data Science and Analytics');
INSERT INTO tutees VALUES ('E9878314', 'Ethel Swaden', 'Life Sciences');
INSERT INTO tutees VALUES ('E0696546', 'Anabella Channer', 'Mathematics');
INSERT INTO tutees VALUES ('E4647314', 'Annecorinne Autin', 'Physics');
INSERT INTO tutees VALUES ('E5431915', 'Brendan Giraux', 'Quantitative Finance');
INSERT INTO tutees VALUES ('E2445236', 'Read Corrao', 'Statistics');
INSERT INTO tutees VALUES ('E4694872', 'Brena Birchall', 'Chinese Language');
INSERT INTO tutees VALUES ('E7195935', 'Tommy Fulstow', 'Chinese Studies');
INSERT INTO tutees VALUES ('E9217755', 'Garek Attac', ' Communications and New Media');
INSERT INTO tutees VALUES ('E8332277', 'Stu Rings', 'Economics');
INSERT INTO tutees VALUES ('E1884950', 'Lila Sayers', 'English Language');
INSERT INTO tutees VALUES ('E3796321', 'Meridith Prestner', 'English Literature');
INSERT INTO tutees VALUES ('E1969189', 'Ruprecht Torregiani', 'Geography');
INSERT INTO tutees VALUES ('E5241934', 'Gian Maclaine', 'Global Studies');
INSERT INTO tutees VALUES ('E8808614', 'Andras Cupitt', 'History ');
INSERT INTO tutees VALUES ('E1542554', 'Ara Lumsden', 'Japanese Studies');
INSERT INTO tutees VALUES ('E4119076', 'Meghann Comar', 'Malay Studies');
INSERT INTO tutees VALUES ('E4224568', 'Edd Neaves', 'Philosophy');
INSERT INTO tutees VALUES ('E3575481', 'Ursola Heliar', ' Political Science');
INSERT INTO tutees VALUES ('E9886289', 'Carol Backes', ' Psychology');
INSERT INTO tutees VALUES ('E7336299', 'Gunilla Yallowley', ' Social Work');
INSERT INTO tutees VALUES ('E8152943', 'Roxanne Fenich', ' Sociology');
INSERT INTO tutees VALUES ('E1605280', 'Hope Duplock', ' South Asian Studies');
INSERT INTO tutees VALUES ('E1747113', 'Tamra Tonner', ' Southeast Asian Studies');
INSERT INTO tutees VALUES ('E1274809', 'Waite Tompion', 'Theatre Studies');
INSERT INTO tutees VALUES ('E4427915', 'Odele Patel', ' Chemistry');
INSERT INTO tutees VALUES ('E8950920', 'Milicent Hammer', 'Data Science and Analytics');
INSERT INTO tutees VALUES ('E2943263', 'Davie Tash', 'Life Sciences');
INSERT INTO tutees VALUES ('E1787250', 'Fonzie Cowderoy', 'Mathematics');
INSERT INTO tutees VALUES ('E2221320', 'Cacilie Sendley', 'Physics');
INSERT INTO tutees VALUES ('E6853087', 'Davin Papa', 'Quantitative Finance');
INSERT INTO tutees VALUES ('E4603778', 'Ansley Ebunoluwa', 'Statistics');
INSERT INTO tutees VALUES ('E6247671', 'Poppy O''''Donnelly', 'Chinese Language');
INSERT INTO tutees VALUES ('E7938107', 'Gino Chatters', 'Chinese Studies');
INSERT INTO tutees VALUES ('E5740545', 'Luz Durtnal', ' Communications and New Media');
INSERT INTO tutees VALUES ('E6113289', 'Nikolas Conibere', 'Economics');
INSERT INTO tutees VALUES ('E1494873', 'Inez Seeborne', 'English Language');
INSERT INTO tutees VALUES ('E9014206', 'Nance Everil', 'English Literature');
INSERT INTO tutees VALUES ('E1816499', 'Thane Cobelli', 'Geography');
INSERT INTO tutees VALUES ('E0760946', 'Margery Hartopp', 'Global Studies');
INSERT INTO tutees VALUES ('E3592494', 'Katheryn Glide', 'History ');
INSERT INTO tutees VALUES ('E0380298', 'Albina Cuttings', 'Japanese Studies');
INSERT INTO tutees VALUES ('E9707444', 'Kary Joanaud', 'Malay Studies');
INSERT INTO tutees VALUES ('E9490864', 'Adam Capstake', 'Philosophy');
INSERT INTO tutees VALUES ('E5871906', 'Pennie Ives', ' Political Science');
INSERT INTO tutees VALUES ('E0585485', 'Kelsey Daveley', ' Psychology');
INSERT INTO tutees VALUES ('E7416643', 'Barton Kelland', ' Social Work');
INSERT INTO tutees VALUES ('E5991636', 'Calida Okell', ' Sociology');
INSERT INTO tutees VALUES ('E5565868', 'Ricardo Bunch', ' South Asian Studies');
INSERT INTO tutees VALUES ('E2000015', 'Homere Yushkin', ' Southeast Asian Studies');
INSERT INTO tutees VALUES ('E6982254', 'Edee Size', 'Theatre Studies');
INSERT INTO tutees VALUES ('E4899632', 'Conney Gantz', ' Chemistry');
INSERT INTO tutees VALUES ('E0840259', 'Saudra Atteridge', 'Data Science and Analytics');
INSERT INTO tutees VALUES ('E6558142', 'Charisse Madelin', 'Life Sciences');
INSERT INTO tutees VALUES ('E5096051', 'Tanney Faldo', 'Mathematics');
INSERT INTO tutees VALUES ('E0237736', 'Roseline Wilkins', 'Physics');
INSERT INTO tutees VALUES ('E9451305', 'Letizia Chauvey', 'Quantitative Finance');
INSERT INTO tutees VALUES ('E5267053', 'Vita Cockhill', 'Statistics');
INSERT INTO tutees VALUES ('E6667935', 'Chiquia McGreary', 'Chinese Language');
INSERT INTO tutees VALUES ('E4213911', 'Isidor Test', 'Chinese Studies');
INSERT INTO tutees VALUES ('E8347387', 'Barbie Basill', ' Communications and New Media');
INSERT INTO tutees VALUES ('E9550642', 'Ailee Harefoot', 'Economics');
INSERT INTO tutees VALUES ('E0703047', 'Byrle Hatzar', 'English Language');
INSERT INTO tutees VALUES ('E4281077', 'Susie Olman', 'English Literature');
INSERT INTO tutees VALUES ('E6326213', 'Charo Folks', 'Geography');
INSERT INTO tutees VALUES ('E2182119', 'Hewie Kindleside', 'Global Studies');
INSERT INTO tutees VALUES ('E8080187', 'Maureene Kimmins', 'History ');
INSERT INTO tutees VALUES ('E7615072', 'Carce Leonard', 'Japanese Studies');
INSERT INTO tutees VALUES ('E5288954', 'Mord Pleat', 'Malay Studies');
INSERT INTO tutees VALUES ('E2304333', 'Roger Steger', 'Philosophy');
INSERT INTO tutees VALUES ('E0717367', 'Kenny Gudgeon', ' Political Science');
INSERT INTO tutees VALUES ('E8339589', 'Burke Treher', ' Psychology');
INSERT INTO tutees VALUES ('E7179357', 'Mersey Chalcot', ' Social Work');
INSERT INTO tutees VALUES ('E2477153', 'Aloin Pareman', ' Sociology');
INSERT INTO tutees VALUES ('E8617515', 'Baird Larkin', ' South Asian Studies');
INSERT INTO tutees VALUES ('E1662304', 'Kimberley Popplestone', ' Southeast Asian Studies');
INSERT INTO tutees VALUES ('E8826747', 'Case Cretney', 'Theatre Studies');
INSERT INTO tutees VALUES ('E7685241', 'Jannelle McPhail', ' Chemistry');
INSERT INTO tutees VALUES ('E8466789', 'Holmes Russi', 'Data Science and Analytics');
INSERT INTO tutees VALUES ('E1728419', 'Meyer Standage', 'Life Sciences');
INSERT INTO tutees VALUES ('E3397037', 'Chev Urpeth', 'Mathematics');
INSERT INTO tutees VALUES ('E1150781', 'Jayme Lorrie', 'Physics');
INSERT INTO tutees VALUES ('E9969120', 'Antonin Ruppele', 'Quantitative Finance');
INSERT INTO tutees VALUES ('E1956917', 'Yves Ramalho', 'Statistics');
INSERT INTO tutees VALUES ('E3794802', 'Sallie Wycliff', 'Chinese Language');
INSERT INTO tutees VALUES ('E1807091', 'Lindsy Woodworth', 'Chinese Studies');
INSERT INTO tutees VALUES ('E5137227', 'Luci Harburtson', ' Communications and New Media');
INSERT INTO tutees VALUES ('E5990813', 'Hagan Sabathe', 'Economics');
INSERT INTO tutees VALUES ('E7732198', 'Alexine Trickey', 'English Language');
INSERT INTO tutees VALUES ('E2119355', 'Hersh Dominighi', 'English Literature');
INSERT INTO tutees VALUES ('E5189494', 'Kellie Aldred', 'Geography');
INSERT INTO tutees VALUES ('E7232815', 'Rustin Kissell', 'Global Studies');
INSERT INTO tutees VALUES ('E4652308', 'Ben Chappelow', 'History ');
INSERT INTO tutees VALUES ('E9600838', 'Jamill Paulsen', 'Japanese Studies');
INSERT INTO tutees VALUES ('E2678046', 'Lynelle Vowdon', 'Malay Studies');
INSERT INTO tutees VALUES ('E1178463', 'Gorden Layzell', 'Philosophy');
INSERT INTO tutees VALUES ('E9231589', 'Roarke Brinicombe', ' Political Science');
INSERT INTO tutees VALUES ('E2127939', 'Kirbie Black', ' Psychology');
INSERT INTO tutees VALUES ('E9097452', 'Henrik Vakhrushev', ' Social Work');
INSERT INTO tutees VALUES ('E7056541', 'Anatollo Ortzen', ' Sociology');
INSERT INTO tutees VALUES ('E6389549', 'Torry Iiannone', ' South Asian Studies');
INSERT INTO tutees VALUES ('E2704852', 'Welsh Josifovitz', ' Southeast Asian Studies');
INSERT INTO tutees VALUES ('E4529511', 'Devonne Rizzo', 'Theatre Studies');
INSERT INTO tutees VALUES ('E3027917', 'Scott Hards', ' Chemistry');
INSERT INTO tutees VALUES ('E0866505', 'Drucie Heymes', 'Data Science and Analytics');
INSERT INTO tutees VALUES ('E7573239', 'Reeta Hoofe', 'Life Sciences');
INSERT INTO tutees VALUES ('E7552787', 'Hatti Le Bosse', 'Mathematics');
INSERT INTO tutees VALUES ('E0791861', 'Darb Erswell', 'Physics');
INSERT INTO tutees VALUES ('E5910390', 'Carrol Thandi', 'Quantitative Finance');
INSERT INTO tutees VALUES ('E1361591', 'Corine Jedrzejewicz', 'Statistics');
INSERT INTO tutees VALUES ('E9474981', 'Patton Sidey', 'Chinese Language');
INSERT INTO tutees VALUES ('E1248316', 'Lilla Ind', 'Chinese Studies');
INSERT INTO tutees VALUES ('E7852167', 'Sidoney Tailby', ' Communications and New Media');
INSERT INTO tutees VALUES ('E4975942', 'Cleon Reeman', 'Economics');
INSERT INTO tutees VALUES ('E3974555', 'Cynde Penkethman', 'English Language');
INSERT INTO tutees VALUES ('E7439089', 'Dean Kas', 'English Literature');
INSERT INTO tutees VALUES ('E2199018', 'Cosme Jarrette', 'Geography');
INSERT INTO tutees VALUES ('E3896499', 'Sebastian Campa', 'Global Studies');
INSERT INTO tutees VALUES ('E0009873', 'Latia O''''Cuddie', 'History ');
INSERT INTO tutees VALUES ('E6535763', 'Mendie Drever', 'Japanese Studies');
INSERT INTO tutees VALUES ('E4900046', 'Marven Howsden', 'Malay Studies');
INSERT INTO tutees VALUES ('E1976520', 'Jacinta Nuccii', 'Philosophy');
INSERT INTO tutees VALUES ('E7837323', 'Annalee Betchley', ' Political Science');
INSERT INTO tutees VALUES ('E7792115', 'Alyda Musgrave', ' Psychology');
INSERT INTO tutees VALUES ('E3817005', 'Amargo Godbert', ' Social Work');
INSERT INTO tutees VALUES ('E8544952', 'Carmine Adshed', ' Sociology');
INSERT INTO tutees VALUES ('E9111121', 'Stevie Prettejohns', ' South Asian Studies');
INSERT INTO tutees VALUES ('E6511386', 'Tito Woodhouse', ' Southeast Asian Studies');
INSERT INTO tutees VALUES ('E2054146', 'Nanni Eunson', 'Theatre Studies');
INSERT INTO tutees VALUES ('E2291663', 'Frank Menego', ' Chemistry');
INSERT INTO tutees VALUES ('E4959842', 'Moreen Nisard', 'Data Science and Analytics');
INSERT INTO tutees VALUES ('E8127750', 'Bertha Bockler', 'Life Sciences');
INSERT INTO tutees VALUES ('E6872367', 'Grissel Calken', 'Mathematics');
INSERT INTO tutees VALUES ('E0013567', 'Ileane Maso', 'Physics');
INSERT INTO tutees VALUES ('E9381960', 'Marco Brereton', 'Quantitative Finance');
INSERT INTO tutees VALUES ('E0107519', 'Aili Ismay', 'Statistics');
INSERT INTO tutees VALUES ('E3367806', 'Paten MacKill', 'Chinese Language');
INSERT INTO tutees VALUES ('E9111627', 'Gardener MacLure', 'Chinese Studies');
INSERT INTO tutees VALUES ('E2053046', 'Galen Cubuzzi', ' Communications and New Media');
INSERT INTO tutees VALUES ('E5115927', 'Moselle Flello', 'Economics');
INSERT INTO tutees VALUES ('E9625862', 'Morrie Linbohm', 'English Language');
INSERT INTO tutees VALUES ('E2798376', 'Lucia Di Batista', 'English Literature');
INSERT INTO tutees VALUES ('E3777079', 'Clemence Murrell', 'Geography');
INSERT INTO tutees VALUES ('E9523722', 'Fancy Camous', 'Global Studies');
INSERT INTO tutees VALUES ('E2694751', 'Cicely Brunner', 'History ');
INSERT INTO tutees VALUES ('E9274943', 'Simonne Vallance', 'Japanese Studies');
INSERT INTO tutees VALUES ('E3370638', 'Beatrice Jonczyk', 'Malay Studies');
INSERT INTO tutees VALUES ('E1894090', 'Nonna Maruszewski', 'Philosophy');
INSERT INTO tutees VALUES ('E1025687', 'Bobette Ishaki', ' Political Science');
INSERT INTO tutees VALUES ('E9351296', 'Amberly Sans', ' Psychology');
INSERT INTO tutees VALUES ('E7666206', 'Abel Munford', ' Social Work');
INSERT INTO tutees VALUES ('E5675723', 'Shelton Tear', ' Sociology');
INSERT INTO tutees VALUES ('E4516984', 'Teodor Benyon', ' South Asian Studies');
INSERT INTO tutees VALUES ('E4703490', 'Agace Chimenti', ' Southeast Asian Studies');
INSERT INTO tutees VALUES ('E9302190', 'Sanders De la Yglesias', 'Theatre Studies');
INSERT INTO tutees VALUES ('E5153294', 'Angy Dudeney', ' Chemistry');
INSERT INTO tutees VALUES ('E2791776', 'Ruggiero Hogbourne', 'Data Science and Analytics');
INSERT INTO tutees VALUES ('E6202420', 'Bennie Lias', 'Life Sciences');
INSERT INTO tutees VALUES ('E5898744', 'Ellynn Agget', 'Mathematics');
INSERT INTO tutees VALUES ('E0202797', 'Cinderella Summerson', 'Physics');
INSERT INTO tutees VALUES ('E0265326', 'Aguste Lunny', 'Quantitative Finance');
INSERT INTO tutees VALUES ('E4959743', 'Arther Velden', 'Statistics');
INSERT INTO tutees VALUES ('E8406631', 'Jacinthe Cone', 'Chinese Language');
INSERT INTO tutees VALUES ('E2640562', 'Ralina Grisedale', 'Chinese Studies');
INSERT INTO tutees VALUES ('E4434871', 'Bertrando Woolbrook', ' Communications and New Media');
INSERT INTO tutees VALUES ('E3727857', 'Honey Dumblton', 'Economics');
INSERT INTO tutees VALUES ('E7519249', 'Estelle Guinness', 'English Language');
INSERT INTO tutees VALUES ('E3609932', 'Rog Lumm', 'English Literature');
INSERT INTO tutees VALUES ('E8583455', 'Leonard Matuskiewicz', 'Geography');
INSERT INTO tutees VALUES ('E5540850', 'Janaya Bonifacio', 'Global Studies');
INSERT INTO tutees VALUES ('E6558405', 'Noni Grebert', 'History ');
INSERT INTO tutees VALUES ('E7318504', 'Godwin Sex', 'Japanese Studies');
INSERT INTO tutees VALUES ('E1049822', 'Marena Fetter', 'Malay Studies');
INSERT INTO tutees VALUES ('E0682189', 'Junette Giddings', 'Philosophy');
INSERT INTO tutees VALUES ('E7896008', 'Granny Heistermann', ' Political Science');
INSERT INTO tutees VALUES ('E4407163', 'Roze Pleager', ' Psychology');
INSERT INTO tutees VALUES ('E1616357', 'Franky Tassell', ' Social Work');
INSERT INTO tutees VALUES ('E2161295', 'Sue Bassano', ' Sociology');
INSERT INTO tutees VALUES ('E0018324', 'Pier Sprankling', ' South Asian Studies');
INSERT INTO tutees VALUES ('E9912413', 'Ira Tolchar', ' Southeast Asian Studies');
INSERT INTO tutees VALUES ('E2523867', 'Willie Vicent', 'Theatre Studies');
INSERT INTO tutees VALUES ('E7724145', 'Noell Favey', ' Chemistry');
INSERT INTO tutees VALUES ('E3357440', 'Willyt Crampsey', 'Data Science and Analytics');
INSERT INTO tutees VALUES ('E1214555', 'Bealle Elcott', 'Life Sciences');
INSERT INTO tutees VALUES ('E5332891', 'Aleta Wheway', 'Mathematics');
INSERT INTO tutees VALUES ('E3994276', 'Allys Crut', 'Physics');
INSERT INTO tutees VALUES ('E7651755', 'Pebrook Pottiphar', 'Quantitative Finance');
INSERT INTO tutees VALUES ('E1693743', 'Janek Gotecliffe', 'Statistics');
INSERT INTO tutees VALUES ('E2369533', 'Aurelia Dzenisenka', 'Chinese Language');
INSERT INTO tutees VALUES ('E7324894', 'Bronnie Farley', 'Chinese Studies');
INSERT INTO tutees VALUES ('E6656418', 'Dorie Banisch', ' Communications and New Media');
INSERT INTO tutees VALUES ('E6445797', 'Nari Cretney', 'Economics');
INSERT INTO tutees VALUES ('E7185648', 'Thibaud Saywood', 'English Language');
INSERT INTO tutees VALUES ('E8903692', 'Aldrich Volker', 'English Literature');
INSERT INTO tutees VALUES ('E9585211', 'Tomlin Zanelli', 'Geography');
INSERT INTO tutees VALUES ('E1010656', 'Clemens Pargent', 'Global Studies');
INSERT INTO tutees VALUES ('E3340725', 'Jorgan Bearsmore', 'History ');
INSERT INTO tutees VALUES ('E1582270', 'Barton Pech', 'Japanese Studies');
INSERT INTO tutees VALUES ('E7843180', 'Mathew Kewley', 'Malay Studies');
INSERT INTO tutees VALUES ('E7922271', 'Lamont Shoulders', 'Philosophy');
INSERT INTO tutees VALUES ('E3412257', 'Adams Wynett', ' Political Science');
INSERT INTO tutees VALUES ('E4629646', 'Prinz Strut', ' Psychology');
INSERT INTO tutees VALUES ('E3845935', 'Dorolice Fairbridge', ' Social Work');
INSERT INTO tutees VALUES ('E0152738', 'Corette Sheppard', ' Sociology');
INSERT INTO tutees VALUES ('E3338786', 'Gregorio Axcel', ' South Asian Studies');
INSERT INTO tutees VALUES ('E0086291', 'Kassia Lawtie', ' Southeast Asian Studies');
INSERT INTO tutees VALUES ('E8609003', 'Bonita Vanyarkin', 'Theatre Studies');
INSERT INTO tutees VALUES ('E8844259', 'Davy Selwin', ' Chemistry');
INSERT INTO tutees VALUES ('E1425032', 'Nathalia Bool', 'Data Science and Analytics');
INSERT INTO tutees VALUES ('E5023044', 'Jennee Curley', 'Life Sciences');
INSERT INTO tutees VALUES ('E2238849', 'Peg Brach', 'Mathematics');
INSERT INTO tutees VALUES ('E4718506', 'Zorah Stammer', 'Physics');
INSERT INTO tutees VALUES ('E7787919', 'Clemence Smickle', 'Quantitative Finance');
INSERT INTO tutees VALUES ('E2037261', 'Clemmie Manie', 'Statistics');
INSERT INTO tutees VALUES ('E8089756', 'Goldy Shimwell', 'Chinese Language');
INSERT INTO tutees VALUES ('E4857302', 'Pearle Coetzee', 'Chinese Studies');
INSERT INTO tutees VALUES ('E3246220', 'De Brosio', ' Communications and New Media');
INSERT INTO tutees VALUES ('E8531569', 'Allix Olczak', 'Economics');
INSERT INTO tutees VALUES ('E7818547', 'Tabbatha Groucock', 'English Language');
INSERT INTO tutees VALUES ('E7095006', 'Pearline Catmull', 'English Literature');
INSERT INTO tutees VALUES ('E7819005', 'Wittie Semonin', 'Geography');
INSERT INTO tutees VALUES ('E1534208', 'Kristan Stanning', 'Global Studies');
INSERT INTO tutees VALUES ('E6856852', 'Florette Andres', 'History ');
INSERT INTO tutees VALUES ('E8923960', 'Kristo Beazley', 'Japanese Studies');
INSERT INTO tutees VALUES ('E8874552', 'Bruno Dusting', 'Malay Studies');
INSERT INTO tutees VALUES ('E6399758', 'Cherilyn Thomke', 'Philosophy');
INSERT INTO tutees VALUES ('E4807599', 'Andras Morrieson', ' Political Science');
INSERT INTO tutees VALUES ('E4213103', 'Ingunna Suston', ' Psychology');
INSERT INTO tutees VALUES ('E1839337', 'Deva Jales', ' Social Work');
INSERT INTO tutees VALUES ('E8965251', 'Lek McGilvra', ' Sociology');
INSERT INTO tutees VALUES ('E5361579', 'Minna Painten', ' South Asian Studies');
INSERT INTO tutees VALUES ('E1974624', 'Leon Dingate', ' Southeast Asian Studies');
INSERT INTO tutees VALUES ('E3505324', 'Pattie Varty', 'Theatre Studies');
INSERT INTO tutees VALUES ('E6053274', 'Johannah De La Coste', ' Chemistry');
INSERT INTO tutees VALUES ('E1343397', 'Paddy Bleesing', 'Data Science and Analytics');
INSERT INTO tutees VALUES ('E0757992', 'Nicol Taleworth', 'Life Sciences');
INSERT INTO tutees VALUES ('E7830834', 'Winslow Hedger', 'Mathematics');
INSERT INTO tutees VALUES ('E9735344', 'Drusi Paulich', 'Physics');
INSERT INTO tutees VALUES ('E7909531', 'Pasquale Chetwynd', 'Quantitative Finance');
INSERT INTO tutees VALUES ('E2336385', 'Lovell Wrankmore', 'Statistics');
INSERT INTO tutees VALUES ('E5239366', 'Lonnie Rawne', 'Chinese Language');
INSERT INTO tutees VALUES ('E6158335', 'Gabbie McCowen', 'Chinese Studies');
INSERT INTO tutees VALUES ('E6814142', 'Marcello Ohrtmann', ' Communications and New Media');
INSERT INTO tutees VALUES ('E7433537', 'Frederic Maulin', 'Economics');
INSERT INTO tutees VALUES ('E5376857', 'Janela Kiljan', 'English Language');
INSERT INTO tutees VALUES ('E9809585', 'Jessey Lind', 'English Literature');
INSERT INTO tutees VALUES ('E0919856', 'Benedetto Eastmond', 'Geography');
INSERT INTO tutees VALUES ('E3359099', 'Lynea Stent', 'Global Studies');
INSERT INTO tutees VALUES ('E1820328', 'Ed Dallow', 'History ');
INSERT INTO tutees VALUES ('E9988973', 'Theressa Alessandretti', 'Japanese Studies');
INSERT INTO tutees VALUES ('E2061498', 'Abdel Methringham', 'Malay Studies');
INSERT INTO tutees VALUES ('E7945354', 'Torin Morit', 'Philosophy');
INSERT INTO tutees VALUES ('E7198338', 'Ezechiel Raddin', ' Political Science');
INSERT INTO tutees VALUES ('E1177413', 'Harold Kirkup', ' Psychology');
INSERT INTO tutees VALUES ('E9512486', 'Ingra Higgen', ' Social Work');
INSERT INTO tutees VALUES ('E7399833', 'Josefina Antoons', ' Sociology');
INSERT INTO tutees VALUES ('E4503513', 'Karen Orford', ' South Asian Studies');
INSERT INTO tutees VALUES ('E8209004', 'Davie Eltone', ' Southeast Asian Studies');
INSERT INTO tutees VALUES ('E3907228', 'Ayn Klamp', 'Theatre Studies');
INSERT INTO tutees VALUES ('E7709579', 'Sheena Laurence', ' Chemistry');
INSERT INTO tutees VALUES ('E2308286', 'Rachel Measey', 'Data Science and Analytics');
INSERT INTO tutees VALUES ('E0528447', 'Ronda Lammas', 'Life Sciences');
INSERT INTO tutees VALUES ('E2342315', 'Carole Ornils', 'Mathematics');
INSERT INTO tutees VALUES ('E3985479', 'Marjie Livings', 'Physics');
INSERT INTO tutees VALUES ('E7345188', 'Edithe Skeech', 'Quantitative Finance');
INSERT INTO tutees VALUES ('E6457211', 'Jacob Chard', 'Statistics');
INSERT INTO tutees VALUES ('E5960577', 'Corina Hagland', 'Chinese Language');
INSERT INTO tutees VALUES ('E7040154', 'Jonathon Cawdell', 'Chinese Studies');
INSERT INTO tutees VALUES ('E7095838', 'Goddard Brandham', ' Communications and New Media');
INSERT INTO tutees VALUES ('E5833758', 'Barton Tremblett', 'Economics');
INSERT INTO tutees VALUES ('E8160970', 'Brent Rawnsley', 'English Language');
INSERT INTO tutees VALUES ('E8429704', 'Orelee Aaronsohn', 'English Literature');
INSERT INTO tutees VALUES ('E1736123', 'Adoree Cannop', 'Geography');
INSERT INTO tutees VALUES ('E2536270', 'Carmel Scalera', 'Global Studies');
INSERT INTO tutees VALUES ('E1949807', 'Aluino Rowbury', 'History ');
INSERT INTO tutees VALUES ('E6093515', 'Vyky Bute', 'Japanese Studies');
INSERT INTO tutees VALUES ('E5063075', 'Cinnamon Haveline', 'Malay Studies');
INSERT INTO tutees VALUES ('E5104281', 'Ellerey Drepp', 'Philosophy');
INSERT INTO tutees VALUES ('E6281813', 'Margalo Abrahamsson', ' Political Science');
INSERT INTO tutees VALUES ('E9071318', 'Richart Hudleston', ' Psychology');
INSERT INTO tutees VALUES ('E9156673', 'Roanne Darko', ' Social Work');
INSERT INTO tutees VALUES ('E7664281', 'Alfonse Beebis', ' Sociology');
INSERT INTO tutees VALUES ('E8908150', 'Minta Ivakhnov', ' South Asian Studies');
INSERT INTO tutees VALUES ('E9305857', 'Moyra Kalinsky', ' Southeast Asian Studies');
INSERT INTO tutees VALUES ('E7988849', 'Godiva Saintpierre', 'Theatre Studies');
INSERT INTO tutees VALUES ('E5813461', 'Ashleigh Dunlop', ' Chemistry');
INSERT INTO tutees VALUES ('E4975124', 'Cicily Golt', 'Data Science and Analytics');
INSERT INTO tutees VALUES ('E3797176', 'Erv Feldbrin', 'Life Sciences');
INSERT INTO tutees VALUES ('E4173702', 'Cherye Dilworth', 'Mathematics');
INSERT INTO tutees VALUES ('E4194043', 'Lane McGettrick', 'Physics');
INSERT INTO tutees VALUES ('E7532357', 'Camille Gilbane', 'Quantitative Finance');
INSERT INTO tutees VALUES ('E8924629', 'Daria Paraman', 'Statistics');
INSERT INTO tutees VALUES ('E8892096', 'Kim Mordue', 'Chinese Language');
INSERT INTO tutees VALUES ('E0220996', 'Arabele McKevin', 'Chinese Studies');
INSERT INTO tutees VALUES ('E3276770', 'Gerek Father', ' Communications and New Media');
INSERT INTO tutees VALUES ('E6181312', 'Nicolle Gorgen', 'Economics');
INSERT INTO tutees VALUES ('E8305069', 'Marjy Kingswoode', 'English Language');
INSERT INTO tutees VALUES ('E0516779', 'Etta Eat', 'English Literature');
INSERT INTO tutees VALUES ('E8799422', 'Maggee Danniell', 'Geography');
INSERT INTO tutees VALUES ('E3824245', 'Paule Dignon', 'Global Studies');
INSERT INTO tutees VALUES ('E3554443', 'Erskine Epsley', 'History ');
INSERT INTO tutees VALUES ('E0487491', 'Michaelina Geere', 'Japanese Studies');
INSERT INTO tutees VALUES ('E7502799', 'Danice Dempsey', 'Malay Studies');
INSERT INTO tutees VALUES ('E3678967', 'Lily Grinin', 'Philosophy');
INSERT INTO tutees VALUES ('E7626595', 'Tobie Despenser', ' Political Science');
INSERT INTO tutees VALUES ('E1637802', 'Nana Crambie', ' Psychology');
INSERT INTO tutees VALUES ('E2163440', 'Dominga Botte', ' Social Work');
INSERT INTO tutees VALUES ('E8503600', 'Berni Atling', ' Sociology');
INSERT INTO tutees VALUES ('E6411896', 'Haleigh Dack', ' South Asian Studies');
INSERT INTO tutees VALUES ('E0327779', 'Cornall Basnett', ' Southeast Asian Studies');
INSERT INTO tutees VALUES ('E5618194', 'Willow Penchen', 'Theatre Studies');
INSERT INTO tutees VALUES ('E1022753', 'Shanna Kesey', ' Chemistry');
INSERT INTO tutees VALUES ('E9302004', 'Belita Aspel', 'Data Science and Analytics');
INSERT INTO tutees VALUES ('E3934602', 'Allsun Pagitt', 'Life Sciences');
INSERT INTO tutees VALUES ('E6449018', 'Roxane Scase', 'Mathematics');
INSERT INTO tutees VALUES ('E3557774', 'Aile Piercey', 'Physics');
INSERT INTO tutees VALUES ('E9825233', 'Vinny Fitt', 'Quantitative Finance');
INSERT INTO tutees VALUES ('E9811394', 'Sashenka Ivanaev', 'Statistics');
INSERT INTO tutees VALUES ('E5185666', 'Cobbie Sleet', 'Chinese Language');
INSERT INTO tutees VALUES ('E7713146', 'Lemar Dorrian', 'Chinese Studies');
INSERT INTO tutees VALUES ('E8149758', 'Giffard Hanley', ' Communications and New Media');
INSERT INTO tutees VALUES ('E9353637', 'Dalenna Sine', 'Economics');
INSERT INTO tutees VALUES ('E3354183', 'Elnore O''''Harney', 'English Language');
INSERT INTO tutees VALUES ('E1403129', 'Claude Perton', 'English Literature');
INSERT INTO tutees VALUES ('E4233630', 'Ilene Clougher', 'Geography');
INSERT INTO tutees VALUES ('E3654515', 'Netty Platts', 'Global Studies');
INSERT INTO tutees VALUES ('E9121447', 'Kinnie Tooker', 'History ');
INSERT INTO tutees VALUES ('E1446312', 'Kalina Bolens', 'Japanese Studies');
INSERT INTO tutees VALUES ('E3850525', 'Cheston Matantsev', 'Malay Studies');
INSERT INTO tutees VALUES ('E7955242', 'Vanessa Goldhawk', 'Philosophy');
INSERT INTO tutees VALUES ('E4697179', 'Gratia McChruiter', ' Political Science');
INSERT INTO tutees VALUES ('E5709239', 'Lurette Ciotti', ' Psychology');
INSERT INTO tutees VALUES ('E2029604', 'Lizbeth Sedgman', ' Social Work');
INSERT INTO tutees VALUES ('E5421106', 'Fiorenze Crawshay', ' Sociology');
INSERT INTO tutees VALUES ('E5325451', 'Lee Kabsch', ' South Asian Studies');
INSERT INTO tutees VALUES ('E4738914', 'Sawyer Scrannage', ' Southeast Asian Studies');
INSERT INTO tutees VALUES ('E4352960', 'Stefano Eim', 'Theatre Studies');
INSERT INTO tutees VALUES ('E9733511', 'Kendricks McNirlan', ' Chemistry');
INSERT INTO tutees VALUES ('E0898695', 'Ninnetta Jirka', 'Data Science and Analytics');
INSERT INTO tutees VALUES ('E5116697', 'Ganny Hordell', 'Life Sciences');
INSERT INTO tutees VALUES ('E0389447', 'Editha MacCombe', 'Mathematics');
INSERT INTO tutees VALUES ('E2992273', 'Corey Atmore', 'Physics');
INSERT INTO tutees VALUES ('E4570295', 'Dan Offord', 'Quantitative Finance');
INSERT INTO tutees VALUES ('E6254332', 'Colver Winley', 'Statistics');
INSERT INTO tutees VALUES ('E3350464', 'Bancroft MacFadin', 'Chinese Language');
INSERT INTO tutees VALUES ('E7703051', 'Mac Glazer', 'Chinese Studies');
INSERT INTO tutees VALUES ('E1792040', 'Edwin Germon', ' Communications and New Media');
INSERT INTO tutees VALUES ('E7471281', 'Tracy Simacek', 'Economics');
INSERT INTO tutees VALUES ('E6795104', 'Devon Charpin', 'English Language');
INSERT INTO tutees VALUES ('E1826390', 'Kyrstin Coram', 'English Literature');
INSERT INTO tutees VALUES ('E9894920', 'Latia Jertz', 'Geography');
INSERT INTO tutees VALUES ('E8333141', 'Alina Braddock', 'Global Studies');
INSERT INTO tutees VALUES ('E0975673', 'Syd Bowland', 'History ');
INSERT INTO tutees VALUES ('E7692603', 'Lari Trittam', 'Japanese Studies');
INSERT INTO tutees VALUES ('E9655524', 'Dita Cleverly', 'Malay Studies');
INSERT INTO tutees VALUES ('E7721094', 'Anya McLaren', 'Philosophy');
INSERT INTO tutees VALUES ('E0646222', 'Rob Hancock', ' Political Science');
INSERT INTO tutees VALUES ('E6961097', 'Abbi Kernoghan', ' Psychology');
INSERT INTO tutees VALUES ('E0089670', 'Otis Kubek', ' Social Work');
INSERT INTO tutees VALUES ('E9971098', 'Margette Wonfar', ' Sociology');
INSERT INTO tutees VALUES ('E8556909', 'Abie Counsell', ' South Asian Studies');
INSERT INTO tutees VALUES ('E6955182', 'Pepillo Granger', ' Southeast Asian Studies');
INSERT INTO tutees VALUES ('E9542301', 'Susette Ferrara', 'Theatre Studies');
INSERT INTO tutees VALUES ('E6275068', 'Randolf Arsmith', ' Chemistry');
INSERT INTO tutees VALUES ('E9337771', 'Giorgio Bartlosz', 'Data Science and Analytics');
INSERT INTO tutees VALUES ('E5245520', 'Tanhya Lethibridge', 'Life Sciences');
INSERT INTO tutees VALUES ('E4272438', 'Danyette Prestige', 'Mathematics');
INSERT INTO tutees VALUES ('E3529498', 'Liesa Rallings', 'Physics');
INSERT INTO tutees VALUES ('E2212717', 'Ricardo Gonthier', 'Quantitative Finance');
INSERT INTO tutees VALUES ('E2006380', 'Darell Jukes', 'Statistics');
INSERT INTO tutees VALUES ('E0392349', 'Carolus Newiss', 'Chinese Language');
INSERT INTO tutees VALUES ('E6695510', 'Judie Erratt', 'Chinese Studies');
INSERT INTO tutees VALUES ('E0984823', 'Letitia Christmas', ' Communications and New Media');
INSERT INTO tutees VALUES ('E5209393', 'Langsdon Loveridge', 'Economics');
INSERT INTO tutees VALUES ('E9146960', 'Loralee O''''Keenan', 'English Language');
INSERT INTO tutees VALUES ('E7623216', 'Jerad Adame', 'English Literature');
INSERT INTO tutees VALUES ('E2280288', 'Joya Lavington', 'Geography');
INSERT INTO tutees VALUES ('E0643869', 'Mommy Skellern', 'Global Studies');
INSERT INTO tutees VALUES ('E7573622', 'Martynne Fittis', 'History ');
INSERT INTO tutees VALUES ('E0109497', 'Calla Peepall', 'Japanese Studies');
INSERT INTO tutees VALUES ('E3204716', 'Evangelina Cuttings', 'Malay Studies');
INSERT INTO tutees VALUES ('E2110083', 'Tricia Arnao', 'Philosophy');
INSERT INTO tutees VALUES ('E8613388', 'Fleurette Bang', ' Political Science');
INSERT INTO tutees VALUES ('E9780335', 'Mort Riepel', ' Psychology');
INSERT INTO tutees VALUES ('E6566205', 'Bevvy Hecks', ' Social Work');
INSERT INTO tutees VALUES ('E3117852', 'Stacee Tyrer', ' Sociology');
INSERT INTO tutees VALUES ('E0030612', 'Caty Squirrel', ' South Asian Studies');
INSERT INTO tutees VALUES ('E3474897', 'Shanda Wightman', ' Southeast Asian Studies');
INSERT INTO tutees VALUES ('E5028299', 'Kincaid Basnett', 'Theatre Studies');
INSERT INTO tutees VALUES ('E5822750', 'Yancey Breddy', ' Chemistry');
INSERT INTO tutees VALUES ('E3699054', 'Coleman Mohammad', 'Data Science and Analytics');
INSERT INTO tutees VALUES ('E1494194', 'Clarissa Kless', 'Life Sciences');
INSERT INTO tutees VALUES ('E9634530', 'Helen Lewinton', 'Mathematics');
INSERT INTO tutees VALUES ('E9013909', 'Kristofor Sperski', 'Physics');
INSERT INTO tutees VALUES ('E7311774', 'Katleen Yantsev', 'Quantitative Finance');
INSERT INTO tutees VALUES ('E2953911', 'Nanice Westwick', 'Statistics');
INSERT INTO tutees VALUES ('E5953312', 'Taddeo Reen', 'Chinese Language');
INSERT INTO tutees VALUES ('E5026486', 'Rowena Lewcock', 'Chinese Studies');
INSERT INTO tutees VALUES ('E6363513', 'Delmer Borne', ' Communications and New Media');
INSERT INTO tutees VALUES ('E1724804', 'Jeff O''''Neil', 'Economics');
INSERT INTO tutees VALUES ('E3773940', 'Tiphani Whysall', 'English Language');
INSERT INTO tutees VALUES ('E7140773', 'Gregorius Blum', 'English Literature');
INSERT INTO tutees VALUES ('E5497821', 'Viviana Sauvage', 'Geography');
INSERT INTO tutees VALUES ('E6526533', 'Stevie Arpe', 'Global Studies');
INSERT INTO tutees VALUES ('E0077989', 'Lorine Govett', 'History ');
INSERT INTO tutees VALUES ('E2134863', 'Yoshiko Forsythe', 'Japanese Studies');
INSERT INTO tutees VALUES ('E3364951', 'Geoffry Robathon', 'Malay Studies');
INSERT INTO tutees VALUES ('E6487348', 'Pammy Isack', 'Philosophy');
INSERT INTO tutees VALUES ('E4690616', 'Bree Corbould', ' Political Science');
INSERT INTO tutees VALUES ('E3698610', 'Trstram Jacques', ' Psychology');
INSERT INTO tutees VALUES ('E9774169', 'Conn Wiz', ' Social Work');
INSERT INTO tutees VALUES ('E8161497', 'Joeann Basey', ' Sociology');
INSERT INTO tutees VALUES ('E6091989', 'Wallas Profit', ' South Asian Studies');
INSERT INTO tutees VALUES ('E4695857', 'Zane McFarlan', ' Southeast Asian Studies');
INSERT INTO tutees VALUES ('E3821399', 'Emmanuel Stocky', 'Theatre Studies');
INSERT INTO tutees VALUES ('E7636427', 'Alessandro Furzer', ' Chemistry');
INSERT INTO tutees VALUES ('E2283395', 'Gerri Cullivan', 'Data Science and Analytics');
INSERT INTO tutees VALUES ('E4789787', 'Andy Lisciardelli', 'Life Sciences');
INSERT INTO tutees VALUES ('E9315246', 'Robbin McGavin', 'Mathematics');
INSERT INTO tutees VALUES ('E0399027', 'Annie Schimann', 'Physics');
INSERT INTO tutees VALUES ('E0276377', 'Mel Gookey', 'Quantitative Finance');
INSERT INTO tutees VALUES ('E6384096', 'Christal Rowaszkiewicz', 'Statistics');
INSERT INTO tutees VALUES ('E3427657', 'Stella Lias', 'Chinese Language');
INSERT INTO tutees VALUES ('E2399331', 'Eulalie Wreak', 'Chinese Studies');
INSERT INTO tutees VALUES ('E8931857', 'Simone Sutliff', ' Communications and New Media');
INSERT INTO tutees VALUES ('E1303787', 'Lefty Duiged', 'Economics');
INSERT INTO tutees VALUES ('E0245977', 'Davine Robertz', 'English Language');
INSERT INTO tutees VALUES ('E8760251', 'Monti Koop', 'English Literature');
INSERT INTO tutees VALUES ('E4104301', 'Nerissa McGenis', 'Geography');
INSERT INTO tutees VALUES ('E2601413', 'Urbanus Culleton', 'Global Studies');
INSERT INTO tutees VALUES ('E4408435', 'Bettine Aleksandrikin', 'History ');
INSERT INTO tutees VALUES ('E2097292', 'Xenos Kislingbury', 'Japanese Studies');
INSERT INTO tutees VALUES ('E9013156', 'Cynthy Fazakerley', 'Malay Studies');
INSERT INTO tutees VALUES ('E9278470', 'Marcos Male', 'Philosophy');
INSERT INTO tutees VALUES ('E9597771', 'Cassy Bridgen', ' Political Science');
INSERT INTO tutees VALUES ('E8835592', 'Catherine Gillease', ' Psychology');
INSERT INTO tutees VALUES ('E7172256', 'Irina Paviour', ' Social Work');
INSERT INTO tutees VALUES ('E0036367', 'Norri Amy', ' Sociology');
INSERT INTO tutees VALUES ('E0638547', 'Tani Buckston', ' South Asian Studies');
INSERT INTO tutees VALUES ('E9740210', 'Trixy Durnin', ' Southeast Asian Studies');
INSERT INTO tutees VALUES ('E3732507', 'Petr Schuricht', 'Theatre Studies');
INSERT INTO tutees VALUES ('E2089045', 'Merrielle Aleksandrikin', ' Chemistry');
INSERT INTO tutees VALUES ('E8718542', 'Luciana Fawcitt', 'Data Science and Analytics');
INSERT INTO tutees VALUES ('E5787537', 'Belle Ridpath', 'Life Sciences');
INSERT INTO tutees VALUES ('E4626457', 'Jerome Walisiak', 'Mathematics');
INSERT INTO tutees VALUES ('E5702708', 'Gian Fumagalli', 'Physics');
INSERT INTO tutees VALUES ('E3617867', 'Ingeborg Truckett', 'Quantitative Finance');
INSERT INTO tutees VALUES ('E2875463', 'Reagan Cure', 'Statistics');
INSERT INTO tutees VALUES ('E7309299', 'Ramsey Krikorian', 'Chinese Language');
INSERT INTO tutees VALUES ('E5270138', 'Crissie Narey', 'Chinese Studies');
INSERT INTO tutees VALUES ('E4923462', 'Thorn Milnes', ' Communications and New Media');
INSERT INTO tutees VALUES ('E6540280', 'Earl Mattiacci', 'Economics');
INSERT INTO tutees VALUES ('E6290386', 'Yanaton Weedall', 'English Language');
INSERT INTO tutees VALUES ('E3346457', 'Ileana Pellman', 'English Literature');
INSERT INTO tutees VALUES ('E1419263', 'Zedekiah Robinett', 'Geography');
INSERT INTO tutees VALUES ('E9636364', 'Garvey Leppingwell', 'Global Studies');
INSERT INTO tutees VALUES ('E5167886', 'Merna Goldsbrough', 'History ');
INSERT INTO tutees VALUES ('E6122675', 'Riki Packington', 'Japanese Studies');
INSERT INTO tutees VALUES ('E3728161', 'Marlon Carnaman', 'Malay Studies');
INSERT INTO tutees VALUES ('E2210925', 'Lewes Belverstone', 'Philosophy');
INSERT INTO tutees VALUES ('E1974912', 'Hirsch Jurek', ' Political Science');
INSERT INTO tutees VALUES ('E6344777', 'Candy Whyffen', ' Psychology');
INSERT INTO tutees VALUES ('E1849495', 'Matelda MacCauley', ' Social Work');
INSERT INTO tutees VALUES ('E9900335', 'Kendal Neggrini', ' Sociology');
INSERT INTO tutees VALUES ('E7704733', 'Chucho Francesconi', ' South Asian Studies');
INSERT INTO tutees VALUES ('E5880113', 'Nev Garlic', ' Southeast Asian Studies');
INSERT INTO tutees VALUES ('E8159219', 'Gabriela Martello', 'Theatre Studies');
INSERT INTO tutees VALUES ('E5785469', 'Lola Shand', ' Chemistry');
INSERT INTO tutees VALUES ('E4614164', 'Humfried Hartgill', 'Data Science and Analytics');
INSERT INTO tutees VALUES ('E7921036', 'Sidnee Aizic', 'Life Sciences');
INSERT INTO tutees VALUES ('E2819459', 'Kettie Tregenna', 'Mathematics');
INSERT INTO tutees VALUES ('E4954483', 'Bradan Zorzutti', 'Physics');
INSERT INTO tutees VALUES ('E5494639', 'Krystle Gollin', 'Quantitative Finance');
INSERT INTO tutees VALUES ('E0769290', 'Irwinn Tokley', 'Statistics');
INSERT INTO tutees VALUES ('E5438754', 'Kev Nottle', 'Chinese Language');
INSERT INTO tutees VALUES ('E3531892', 'Bevan Bavridge', 'Chinese Studies');
INSERT INTO tutees VALUES ('E3890663', 'Greer Tassell', ' Communications and New Media');
INSERT INTO tutees VALUES ('E5558844', 'Jean Eggleson', 'Economics');
INSERT INTO tutees VALUES ('E6421828', 'Salvidor Thecham', 'English Language');
INSERT INTO tutees VALUES ('E2478375', 'Huntlee Boodle', 'English Literature');
INSERT INTO tutees VALUES ('E1914366', 'Thorvald Castellanos', 'Geography');
INSERT INTO tutees VALUES ('E4477254', 'Cleon Arro', 'Global Studies');
INSERT INTO tutees VALUES ('E1729207', 'Elva Leavens', 'History ');
INSERT INTO tutees VALUES ('E0829914', 'Phyllis Maldin', 'Japanese Studies');
INSERT INTO tutees VALUES ('E5990615', 'Alli O''''Kieran', 'Malay Studies');
INSERT INTO tutees VALUES ('E2868753', 'Dill Michal', 'Philosophy');
INSERT INTO tutees VALUES ('E1421108', 'Holt Gisby', ' Political Science');
INSERT INTO tutees VALUES ('E2503266', 'Fremont Cabble', ' Psychology');
INSERT INTO tutees VALUES ('E4598090', 'Blakelee Lathey', ' Social Work');
INSERT INTO tutees VALUES ('E2849528', 'Barb Pinn', ' Sociology');
INSERT INTO tutees VALUES ('E6664675', 'Darby Kissock', ' South Asian Studies');
INSERT INTO tutees VALUES ('E0032148', 'Sterling Van der Hoven', ' Southeast Asian Studies');
INSERT INTO tutees VALUES ('E2668677', 'Veronica Pietraszek', 'Theatre Studies');
INSERT INTO tutees VALUES ('E3298664', 'Danya Ritzman', ' Chemistry');
INSERT INTO tutees VALUES ('E0490656', 'Datha Nano', 'Data Science and Analytics');
INSERT INTO tutees VALUES ('E8170701', 'Milli Gilyott', 'Life Sciences');
INSERT INTO tutees VALUES ('E9346790', 'Johnny Bolf', 'Mathematics');
INSERT INTO tutees VALUES ('E5647113', 'Gwyn Gundry', 'Physics');
INSERT INTO tutees VALUES ('E8162162', 'Crin Draisey', 'Quantitative Finance');
INSERT INTO tutees VALUES ('E6178768', 'Skell Halton', 'Statistics');
INSERT INTO tutees VALUES ('E5819600', 'Urson Chapman', 'Chinese Language');
INSERT INTO tutees VALUES ('E8357087', 'Xenia Dullingham', 'Chinese Studies');
INSERT INTO tutees VALUES ('E2960953', 'Mathe Forlonge', ' Communications and New Media');
INSERT INTO tutees VALUES ('E9934868', 'Brit Klassman', 'Economics');
INSERT INTO tutees VALUES ('E6721345', 'Maegan Minci', 'English Language');
INSERT INTO tutees VALUES ('E9521742', 'Ivor MacPike', 'English Literature');
INSERT INTO tutees VALUES ('E6453774', 'Trenton Camden', 'Geography');
INSERT INTO tutees VALUES ('E9328021', 'Sheri Arnett', 'Global Studies');
INSERT INTO tutees VALUES ('E3401111', 'Humfrey Ritchings', 'History ');
INSERT INTO tutees VALUES ('E8687348', 'Jacinda Dewan', 'Japanese Studies');
INSERT INTO tutees VALUES ('E8874356', 'Elora Davidofski', 'Malay Studies');
INSERT INTO tutees VALUES ('E7133044', 'Benedict Fillary', 'Philosophy');
INSERT INTO tutees VALUES ('E4742861', 'Gunter Sijmons', ' Political Science');
INSERT INTO tutees VALUES ('E1693229', 'Davida Hilley', ' Psychology');
INSERT INTO tutees VALUES ('E9359548', 'Irene Emps', ' Social Work');
INSERT INTO tutees VALUES ('E5543886', 'Dominik Kopfer', ' Sociology');
INSERT INTO tutees VALUES ('E5947092', 'Othella Seligson', ' South Asian Studies');
INSERT INTO tutees VALUES ('E0631800', 'Mac Screech', ' Southeast Asian Studies');
INSERT INTO tutees VALUES ('E0338852', 'Tully Tarrant', 'Theatre Studies');
INSERT INTO tutees VALUES ('E8630083', 'Emilia Beauly', ' Chemistry');
INSERT INTO tutees VALUES ('E5609283', 'Regan Hugill', 'Data Science and Analytics');
INSERT INTO tutees VALUES ('E6807598', 'Janaya Grinnikov', 'Life Sciences');
INSERT INTO tutees VALUES ('E5612690', 'Hayward Buessen', 'Mathematics');
INSERT INTO tutees VALUES ('E1342736', 'Dewey Burchall', 'Physics');
INSERT INTO tutees VALUES ('E9913209', 'Les Prozescky', 'Quantitative Finance');
INSERT INTO tutees VALUES ('E0244784', 'Marianne Seiffert', 'Statistics');
INSERT INTO tutees VALUES ('E2343922', 'Lurleen Ezzle', 'Chinese Language');
INSERT INTO tutees VALUES ('E8515040', 'Joscelin Casarini', 'Chinese Studies');
INSERT INTO tutees VALUES ('E5727492', 'Dorene Luckie', ' Communications and New Media');
INSERT INTO tutees VALUES ('E3992425', 'Hoebart Sansome', 'Economics');
INSERT INTO tutees VALUES ('E0712131', 'Andrus Mattersey', 'English Language');
INSERT INTO tutees VALUES ('E8830834', 'Dorice Basnett', 'English Literature');
INSERT INTO tutees VALUES ('E2764742', 'Windham Digwood', 'Geography');
INSERT INTO tutees VALUES ('E1250659', 'Vidovik Polkinhorn', 'Global Studies');
INSERT INTO tutees VALUES ('E7648405', 'Jinny Maxstead', 'History ');
INSERT INTO tutees VALUES ('E8727370', 'Myrlene Songer', 'Japanese Studies');
INSERT INTO tutees VALUES ('E4566541', 'Leia Holworth', 'Malay Studies');
INSERT INTO tutees VALUES ('E2989438', 'Talbot Langlais', 'Philosophy');
INSERT INTO tutees VALUES ('E5190241', 'Armstrong O'''' Donohue', ' Political Science');
INSERT INTO tutees VALUES ('E0475545', 'Toddie Hearsey', ' Psychology');
INSERT INTO tutees VALUES ('E9836304', 'Patricia Fittis', ' Social Work');
INSERT INTO tutees VALUES ('E7053353', 'Abel Toler', ' Sociology');
INSERT INTO tutees VALUES ('E0330536', 'Shelia Helliker', ' South Asian Studies');
INSERT INTO tutees VALUES ('E5516686', 'Essa Reggler', ' Southeast Asian Studies');
INSERT INTO tutees VALUES ('E1041022', 'Augustin Chadband', 'Theatre Studies');
INSERT INTO tutees VALUES ('E6242452', 'Gelya Jouhandeau', ' Chemistry');
INSERT INTO tutees VALUES ('E2733684', 'Emelita Bare', 'Data Science and Analytics');
INSERT INTO tutees VALUES ('E5821783', 'Eal Clyant', 'Life Sciences');
INSERT INTO tutees VALUES ('E5056447', 'Tiffy Desbrow', 'Mathematics');
INSERT INTO tutees VALUES ('E2419364', 'Jade Moultrie', 'Physics');
INSERT INTO tutees VALUES ('E7528305', 'Vic Durkin', 'Quantitative Finance');
INSERT INTO tutees VALUES ('E8456746', 'Sol Sargerson', 'Statistics');
INSERT INTO tutees VALUES ('E2614329', 'Kirsteni Wudeland', 'Chinese Language');
INSERT INTO tutees VALUES ('E4851942', 'Zorine Pinchin', 'Chinese Studies');
INSERT INTO tutees VALUES ('E5802654', 'Celesta Tooley', ' Communications and New Media');
INSERT INTO tutees VALUES ('E8503140', 'Mortimer Burbank', 'Economics');
INSERT INTO tutees VALUES ('E5093273', 'Marion Rodolfi', 'English Language');
INSERT INTO tutees VALUES ('E5729784', 'Donnamarie Bundy', 'English Literature');
INSERT INTO tutees VALUES ('E6337907', 'Cassandra Bartaloni', 'Geography');
INSERT INTO tutees VALUES ('E8520744', 'Lesya Gullan', 'Global Studies');
INSERT INTO tutees VALUES ('E3203295', 'Wadsworth Morfey', 'History ');
INSERT INTO tutees VALUES ('E0104442', 'Catha Ruggles', 'Japanese Studies');
INSERT INTO tutees VALUES ('E9895209', 'Myriam Gye', 'Malay Studies');
INSERT INTO tutees VALUES ('E0664779', 'Cull Kirgan', 'Philosophy');
INSERT INTO tutees VALUES ('E9836913', 'Almeria Auden', ' Political Science');
INSERT INTO tutees VALUES ('E0331115', 'Tamera Rawe', ' Psychology');
INSERT INTO tutees VALUES ('E9134126', 'Lucky Brisset', ' Social Work');
INSERT INTO tutees VALUES ('E4701704', 'Kirsti Borrett', ' Sociology');
INSERT INTO tutees VALUES ('E7708382', 'Glory Chasmor', ' South Asian Studies');
INSERT INTO tutees VALUES ('E4555809', 'Florina McColgan', ' Southeast Asian Studies');
INSERT INTO tutees VALUES ('E9072701', 'Sabina Hughesdon', 'Theatre Studies');
INSERT INTO tutees VALUES ('E4267313', 'Ive Jelfs', ' Chemistry');
INSERT INTO tutees VALUES ('E2830368', 'Alvy Harbron', 'Data Science and Analytics');
INSERT INTO tutees VALUES ('E5401208', 'Yorke Casassa', 'Life Sciences');
INSERT INTO tutees VALUES ('E7581235', 'Micah Munnings', 'Mathematics');
INSERT INTO tutees VALUES ('E1758755', 'Serene Gelsthorpe', 'Physics');
INSERT INTO tutees VALUES ('E0129527', 'Leona Zorzini', 'Quantitative Finance');
INSERT INTO tutees VALUES ('E9307180', 'Seka Antoniottii', 'Statistics');
INSERT INTO tutees VALUES ('E6050604', 'Sunny Joderli', 'Chinese Language');
INSERT INTO tutees VALUES ('E8965337', 'Emmye Sola', 'Chinese Studies');
INSERT INTO tutees VALUES ('E9002469', 'Benita Gilphillan', ' Communications and New Media');
INSERT INTO tutees VALUES ('E3539475', 'Rex Dreghorn', 'Economics');
INSERT INTO tutees VALUES ('E6662484', 'Brigham Ninotti', 'English Language');
INSERT INTO tutees VALUES ('E1016991', 'Ermin D''''Onise', 'English Literature');
INSERT INTO tutees VALUES ('E1822150', 'Adara Hallihane', 'Geography');
INSERT INTO tutees VALUES ('E5370840', 'Duffie todor', 'Global Studies');
INSERT INTO tutees VALUES ('E4847333', 'Felisha Deehan', 'History ');
INSERT INTO tutees VALUES ('E5167586', 'Osborne Ganderton', 'Japanese Studies');
INSERT INTO tutees VALUES ('E7858532', 'Emogene Ruvel', 'Malay Studies');
INSERT INTO tutees VALUES ('E1762480', 'Edsel Acory', 'Philosophy');
INSERT INTO tutees VALUES ('E1245855', 'Sheff Foskew', ' Political Science');
INSERT INTO tutees VALUES ('E2095033', 'Emmalynn Benkhe', ' Psychology');
INSERT INTO tutees VALUES ('E5560836', 'Lark Kryska', ' Social Work');
INSERT INTO tutees VALUES ('E8319510', 'Shurlock Dumbar', ' Sociology');
INSERT INTO tutees VALUES ('E0243795', 'Marcy Doogue', ' South Asian Studies');
INSERT INTO tutees VALUES ('E6638831', 'Andie Longmate', ' Southeast Asian Studies');
INSERT INTO tutees VALUES ('E1788521', 'Appolonia Geggie', 'Theatre Studies');
INSERT INTO tutees VALUES ('E3848900', 'Cherice Kidwell', ' Chemistry');
INSERT INTO tutees VALUES ('E6994469', 'Frederick Peattie', 'Data Science and Analytics');
INSERT INTO tutees VALUES ('E7349615', 'Cassandre McMahon', 'Life Sciences');
INSERT INTO tutees VALUES ('E4152795', 'Gwendolen Smales', 'Mathematics');
INSERT INTO tutees VALUES ('E6164942', 'Ruby Penketh', 'Physics');
INSERT INTO tutees VALUES ('E4070686', 'Danica Farryann', 'Quantitative Finance');
INSERT INTO tutees VALUES ('E6039324', 'Stace Priest', 'Statistics');
INSERT INTO tutees VALUES ('E7229037', 'Keen Seville', 'Chinese Language');
INSERT INTO tutees VALUES ('E8488309', 'Ian Pipet', 'Chinese Studies');
INSERT INTO tutees VALUES ('E5374316', 'Jeremie Vlasin', ' Communications and New Media');
INSERT INTO tutees VALUES ('E3347070', 'Paulita Greensted', 'Economics');
INSERT INTO tutees VALUES ('E3065070', 'Albertina Beggin', 'English Language');
INSERT INTO tutees VALUES ('E1632813', 'Albertina Thripp', 'English Literature');
INSERT INTO tutees VALUES ('E6803624', 'Cos Eilers', 'Geography');
INSERT INTO tutees VALUES ('E9054248', 'Cameron MacTerrelly', 'Global Studies');
INSERT INTO tutees VALUES ('E5486203', 'Lorinda Harryman', 'History ');
INSERT INTO tutees VALUES ('E3495871', 'Moyra Le Ball', 'Japanese Studies');
INSERT INTO tutees VALUES ('E1882218', 'Nadiya McLuckie', 'Malay Studies');
INSERT INTO tutees VALUES ('E3423163', 'Townie Proudler', 'Philosophy');
INSERT INTO tutees VALUES ('E5001223', 'Spence Clewlowe', ' Political Science');
INSERT INTO tutees VALUES ('E2970111', 'Malva Burkett', ' Psychology');
INSERT INTO tutees VALUES ('E7123972', 'Karna Lorraine', ' Social Work');
INSERT INTO tutees VALUES ('E9939131', 'Nancy Cordeux', ' Sociology');
INSERT INTO tutees VALUES ('E2832068', 'Pier Lawles', ' South Asian Studies');
INSERT INTO tutees VALUES ('E3709245', 'Leonelle Challenor', ' Southeast Asian Studies');
INSERT INTO tutees VALUES ('E3485336', 'Fancie Mickan', 'Theatre Studies');
INSERT INTO tutees VALUES ('E7857631', 'Godfree Riping', ' Chemistry');
INSERT INTO tutees VALUES ('E0445143', 'Donn Isselee', 'Data Science and Analytics');
INSERT INTO tutees VALUES ('E1118603', 'Livvyy Pietrowicz', 'Life Sciences');
INSERT INTO tutees VALUES ('E7578880', 'Karole Keenlyside', 'Mathematics');
INSERT INTO tutees VALUES ('E3180973', 'Doris Shields', 'Physics');
INSERT INTO tutees VALUES ('E8868981', 'Aaren Simanek', 'Quantitative Finance');
INSERT INTO tutees VALUES ('E5441537', 'Leilah Bentham3', 'Statistics');
INSERT INTO tutees VALUES ('E9090909', 'Tristan Lemmen', 'Chinese Language');
INSERT INTO tutees VALUES ('E2273652', 'Mariejeanne Tolland', 'Chinese Studies');
INSERT INTO tutees VALUES ('E5966350', 'Derk Inold', ' Communications and New Media');
INSERT INTO tutees VALUES ('E1463559', 'Caren Cordey', 'Economics');
INSERT INTO tutees VALUES ('E6184026', 'Collette Birrane', 'English Language');
INSERT INTO tutees VALUES ('E8989761', 'Danette Ost', 'English Literature');
INSERT INTO tutees VALUES ('E2858174', 'Kelly McGrale', 'Geography');
INSERT INTO tutees VALUES ('E8890760', 'Colby Lettsom', 'Global Studies');
INSERT INTO tutees VALUES ('E1471804', 'Nanci Ekins', 'History ');
INSERT INTO tutees VALUES ('E7198279', 'Archaimbaud Osbourne', 'Japanese Studies');
INSERT INTO tutees VALUES ('E1587235', 'Janeta Lindstedt', 'Malay Studies');
INSERT INTO tutees VALUES ('E4397922', 'Alix Danshin', 'Philosophy');
INSERT INTO tutees VALUES ('E2206321', 'Caren Bendelow', ' Political Science');
INSERT INTO tutees VALUES ('E3065674', 'Gustav Wardesworth', ' Psychology');
INSERT INTO tutees VALUES ('E3387800', 'Marius Patching', ' Social Work');
INSERT INTO tutees VALUES ('E9573959', 'Hyacinth Emmer', ' Sociology');
INSERT INTO tutees VALUES ('E4250895', 'Barrett Wattisham', ' South Asian Studies');
INSERT INTO tutees VALUES ('E6130333', 'Anallise Riccioppo', ' Southeast Asian Studies');
INSERT INTO tutees VALUES ('E3070600', 'Dagny MacKall', 'Theatre Studies');
INSERT INTO tutees VALUES ('E1399293', 'Devonna Dilgarno', ' Chemistry');
INSERT INTO tutees VALUES ('E0554436', 'Randi Bohlin', 'Data Science and Analytics');
INSERT INTO tutees VALUES ('E1060945', 'Giselle Dargan', 'Life Sciences');
INSERT INTO tutees VALUES ('E1202897', 'Merry Yair', 'Mathematics');
INSERT INTO tutees VALUES ('E3981925', 'Benn Gorbell', 'Physics');
INSERT INTO tutees VALUES ('E5807131', 'Janela Hincks', 'Quantitative Finance');
INSERT INTO tutees VALUES ('E0520053', 'Bastien MacKeeg', 'Statistics');
INSERT INTO tutees VALUES ('E7080425', 'Leonelle Viccary', 'Chinese Language');
INSERT INTO tutees VALUES ('E6339603', 'Kathye Ibbeson', 'Chinese Studies');
INSERT INTO tutees VALUES ('E5245084', 'Darren Derricoat', ' Communications and New Media');
INSERT INTO tutees VALUES ('E2502501', 'Rozanne Futcher', 'Economics');
INSERT INTO tutees VALUES ('E5836878', 'Rosemaria Barrett', 'English Language');
INSERT INTO tutees VALUES ('E3909603', 'Emilie Ruppeli', 'English Literature');
INSERT INTO tutees VALUES ('E1855942', 'Bentley Stinson', 'Geography');
INSERT INTO tutees VALUES ('E0909450', 'Germayne Chainey', 'Global Studies');
INSERT INTO tutees VALUES ('E6917003', 'Jaynell Jiles', 'History ');
INSERT INTO tutees VALUES ('E3302446', 'Artie Presslie', 'Japanese Studies');
INSERT INTO tutees VALUES ('E2756555', 'Zola Gronow', 'Malay Studies');
INSERT INTO tutees VALUES ('E1721870', 'Ania Flasby', 'Philosophy');
INSERT INTO tutees VALUES ('E9146167', 'Bennie O''''Kennedy', ' Political Science');
INSERT INTO tutees VALUES ('E6120310', 'Hewie Dinjes', ' Psychology');
INSERT INTO tutees VALUES ('E4212597', 'Mikaela McNabb', ' Social Work');
INSERT INTO tutees VALUES ('E9715524', 'Ermengarde Cancutt', ' Sociology');
INSERT INTO tutees VALUES ('E0651975', 'Nikolia Hulkes', ' South Asian Studies');
INSERT INTO tutees VALUES ('E6909051', 'Gui O''''Curran', ' Southeast Asian Studies');
INSERT INTO tutees VALUES ('E4161808', 'Georges Teasey', 'Theatre Studies');
INSERT INTO tutees VALUES ('E4496994', 'Nahum Kildale', ' Chemistry');
INSERT INTO tutees VALUES ('E7153602', 'Cleveland Gatheridge', 'Data Science and Analytics');
INSERT INTO tutees VALUES ('E7963616', 'Myer Rime', 'Life Sciences');
INSERT INTO tutees VALUES ('E5107234', 'Gay Tedridge', 'Mathematics');
INSERT INTO tutees VALUES ('E6626873', 'Mart Edyson', 'Physics');
INSERT INTO tutees VALUES ('E0108862', 'Karissa Elsegood', 'Quantitative Finance');
INSERT INTO tutees VALUES ('E4001882', 'Collen Walby', 'Statistics');
INSERT INTO tutees VALUES ('E1347089', 'Lynn Craigmile', 'Chinese Language');
INSERT INTO tutees VALUES ('E7853161', 'Ramonda Reah', 'Chinese Studies');
INSERT INTO tutees VALUES ('E3476163', 'Jason Thomasset', ' Communications and New Media');
INSERT INTO tutees VALUES ('E4014176', 'Karon Brinsden', 'Economics');
INSERT INTO tutees VALUES ('E4500740', 'Harbert Shieldon', 'English Language');
INSERT INTO tutees VALUES ('E2312609', 'Jonas Gantzer', 'English Literature');
INSERT INTO tutees VALUES ('E3693524', 'Sigfried Rawkesby', 'Geography');
INSERT INTO tutees VALUES ('E8415168', 'Danette Stanes', 'Global Studies');
INSERT INTO tutees VALUES ('E5619571', 'Consuelo Sheepy', 'History ');
INSERT INTO tutees VALUES ('E3068448', 'Cassandry Hallibone', 'Japanese Studies');
INSERT INTO tutees VALUES ('E4747835', 'Michaella Fruish', 'Malay Studies');
INSERT INTO tutees VALUES ('E0249546', 'Deina Bowerbank', 'Philosophy');
INSERT INTO tutees VALUES ('E7639044', 'Bonni Linebarger', ' Political Science');
INSERT INTO tutees VALUES ('E8319484', 'Rosetta Norgate', ' Psychology');
INSERT INTO tutees VALUES ('E3440019', 'Nelle Shawcross', ' Social Work');
INSERT INTO tutees VALUES ('E5264786', 'Binnie Van den Broek', ' Sociology');
INSERT INTO tutees VALUES ('E0266483', 'Kristy Vigrass', ' South Asian Studies');
INSERT INTO tutees VALUES ('E6207184', 'Rowena Fosse', ' Southeast Asian Studies');
INSERT INTO tutees VALUES ('E5701875', 'Kellen Kesteven', 'Theatre Studies');
INSERT INTO tutees VALUES ('E4089929', 'Moina Methringham', ' Chemistry');
INSERT INTO tutees VALUES ('E5834444', 'Roxi Meier', 'Data Science and Analytics');
INSERT INTO tutees VALUES ('E3040345', 'Ebonee Jephson', 'Life Sciences');
INSERT INTO tutees VALUES ('E0769387', 'Jackqueline Rosenbloom', 'Mathematics');
INSERT INTO tutees VALUES ('E3839035', 'Olag Shallcross', 'Physics');
INSERT INTO tutees VALUES ('E6167120', 'Adrian Emsley', 'Quantitative Finance');
INSERT INTO tutees VALUES ('E9580805', 'Krystal Skrines', 'Statistics');
INSERT INTO tutees VALUES ('E7196244', 'Shelden Guichard', 'Chinese Language');
INSERT INTO tutees VALUES ('E0585196', 'Melloney MacTimpany', 'Chinese Studies');
INSERT INTO tutees VALUES ('E1313353', 'Joey Walduck', ' Communications and New Media');
INSERT INTO tutees VALUES ('E8818435', 'Petey Berford', 'Economics');
INSERT INTO tutees VALUES ('E6471703', 'Quillan Kendrick', 'English Language');
INSERT INTO tutees VALUES ('E3849824', 'Jourdain Baert', 'English Literature');
INSERT INTO tutees VALUES ('E9416055', 'Elinore Searsby', 'Geography');
INSERT INTO tutees VALUES ('E6886959', 'Waverley Wagge', 'Global Studies');
INSERT INTO tutees VALUES ('E8737524', 'Shawn Vyel', 'History ');
INSERT INTO tutees VALUES ('E3442709', 'Asher Confort', 'Japanese Studies');
INSERT INTO tutees VALUES ('E5597160', 'Milissent Uttley', 'Malay Studies');
INSERT INTO tutees VALUES ('E7262417', 'Ian Gwynne', 'Philosophy');
INSERT INTO tutees VALUES ('E8243062', 'Wat O''''Heyne', ' Political Science');
INSERT INTO tutees VALUES ('E5138974', 'Sutton Troyes', ' Psychology');
INSERT INTO tutees VALUES ('E6454819', 'Mareah Peckett', ' Social Work');
INSERT INTO tutees VALUES ('E0848033', 'Carney Oldmeadow', ' Sociology');
INSERT INTO tutees VALUES ('E3883543', 'Lorinda Roswarn', ' South Asian Studies');
INSERT INTO tutees VALUES ('E1642939', 'Maude Ballingal', ' Southeast Asian Studies');
INSERT INTO tutees VALUES ('E4805448', 'Ingaborg Meikle', 'Theatre Studies');
INSERT INTO tutees VALUES ('E5645562', 'Selig Shawley', ' Chemistry');
INSERT INTO tutees VALUES ('E8262200', 'Frasquito Hobbert', 'Data Science and Analytics');
INSERT INTO tutees VALUES ('E8990594', 'Aura Setchell', 'Life Sciences');
INSERT INTO tutees VALUES ('E1042104', 'Evin Alibone', 'Mathematics');
INSERT INTO tutees VALUES ('E1648371', 'Marisa Wilcox', 'Physics');
INSERT INTO tutees VALUES ('E9355577', 'Suzie Thombleson', 'Quantitative Finance');
INSERT INTO tutees VALUES ('E0191753', 'Tobey Osmar', 'Statistics');
INSERT INTO tutees VALUES ('E0432697', 'Cornela Shiell', 'Chinese Language');
INSERT INTO tutees VALUES ('E9930295', 'Wanids Kleinstern', 'Chinese Studies');
INSERT INTO tutees VALUES ('E0191108', 'Mic Graundisson', ' Communications and New Media');
INSERT INTO tutees VALUES ('E2810641', 'Bianca Couve', 'Economics');
INSERT INTO tutees VALUES ('E8280298', 'Karlis Gymlett', 'English Language');
INSERT INTO tutees VALUES ('E8553286', 'Morse Drever', 'English Literature');
INSERT INTO tutees VALUES ('E0327257', 'Ellwood Arbor', 'Geography');
INSERT INTO tutees VALUES ('E8494095', 'Elvyn Woolen', 'Global Studies');
INSERT INTO tutees VALUES ('E5213738', 'Liva Cavanagh', 'History ');
INSERT INTO tutees VALUES ('E6895232', 'Prue Evenett', 'Japanese Studies');
INSERT INTO tutees VALUES ('E2149959', 'Micky Brager', 'Malay Studies');
INSERT INTO tutees VALUES ('E2434701', 'Arnoldo Kernan', 'Philosophy');
INSERT INTO tutees VALUES ('E6241617', 'Aggie Jouaneton', ' Political Science');
INSERT INTO tutees VALUES ('E9835353', 'Bram Maber', ' Psychology');
INSERT INTO tutees VALUES ('E6097023', 'Francine Pardie', ' Social Work');
INSERT INTO tutees VALUES ('E2223262', 'Haven Beetham', ' Sociology');
INSERT INTO tutees VALUES ('E7878479', 'Remy Foard', ' South Asian Studies');
INSERT INTO tutees VALUES ('E5235142', 'Robb Chataignier', ' Southeast Asian Studies');
INSERT INTO tutees VALUES ('E1440348', 'Norry Snarr', 'Theatre Studies');
INSERT INTO tutees VALUES ('E6721186', 'Mitchael Felmingham', ' Chemistry');
INSERT INTO tutees VALUES ('E5592732', 'Kerr Coundley', 'Data Science and Analytics');
INSERT INTO tutees VALUES ('E7794857', 'Marthena Keningley', 'Life Sciences');
INSERT INTO tutees VALUES ('E1685356', 'Aretha Demkowicz', 'Mathematics');
INSERT INTO tutees VALUES ('E5941460', 'Nadine Solly', 'Physics');
INSERT INTO tutees VALUES ('E8504964', 'Caterina Chilcotte', 'Quantitative Finance');
INSERT INTO tutees VALUES ('E9378385', 'Ynez Grantham', 'Statistics');
INSERT INTO tutees VALUES ('E7521344', 'Mikaela Bracken', 'Chinese Language');
INSERT INTO tutees VALUES ('E6133179', 'Fabien McDade', 'Chinese Studies');
INSERT INTO tutees VALUES ('E5758439', 'Adah Mains', ' Communications and New Media');
INSERT INTO tutees VALUES ('E3330891', 'Starlin Anyon', 'Economics');
INSERT INTO tutees VALUES ('E8333965', 'Serena Alloisi', 'English Language');
INSERT INTO tutees VALUES ('E5029089', 'Teri Annott', 'English Literature');
INSERT INTO tutees VALUES ('E0365772', 'Cilka Heathcott', 'Geography');
INSERT INTO tutees VALUES ('E2834791', 'Anica Gutcher', 'Global Studies');
INSERT INTO tutees VALUES ('E5208016', 'Quint Bladen', 'History ');
INSERT INTO tutees VALUES ('E7777759', 'Arvie Soigne', 'Japanese Studies');
INSERT INTO tutees VALUES ('E5400098', 'Kain McEwan', 'Malay Studies');
INSERT INTO tutees VALUES ('E0067953', 'Francisco Wyllcock', 'Philosophy');
INSERT INTO tutees VALUES ('E3971439', 'Liza Brogiotti', ' Political Science');
INSERT INTO tutees VALUES ('E9447008', 'Claude Rowles', ' Psychology');
INSERT INTO tutees VALUES ('E0461204', 'Hadley Hackleton', ' Social Work');
INSERT INTO tutees VALUES ('E1933617', 'Ardath Pennings', ' Sociology');
INSERT INTO tutees VALUES ('E8182679', 'Alf Mullaly', ' South Asian Studies');
INSERT INTO tutees VALUES ('E3811340', 'David Watkins', ' Southeast Asian Studies');
INSERT INTO tutees VALUES ('E5445484', 'Wittie Munkton', 'Theatre Studies');
INSERT INTO tutees VALUES ('E7219205', 'Brittany Witter', ' Chemistry');
INSERT INTO tutees VALUES ('E9235836', 'Benjy Stanislaw', 'Data Science and Analytics');
INSERT INTO tutees VALUES ('E7027130', 'Liuka Matteuzzi', 'Life Sciences');
INSERT INTO tutees VALUES ('E8048697', 'Che Cains', 'Mathematics');
INSERT INTO tutees VALUES ('E1444898', 'Gae Howse', 'Physics');
INSERT INTO tutees VALUES ('E2644472', 'Lyssa Ruos', 'Quantitative Finance');
INSERT INTO tutees VALUES ('E3280840', 'Wilmar Allabarton', 'Statistics');
INSERT INTO tutees VALUES ('E0686609', 'Linnie Perle', 'Chinese Language');
INSERT INTO tutees VALUES ('E3493013', 'Kile Reubel', 'Chinese Studies');
INSERT INTO tutees VALUES ('E1247916', 'Tildie Lawry', ' Communications and New Media');
INSERT INTO tutees VALUES ('E5574483', 'Leeland Fardo', 'Economics');
INSERT INTO tutees VALUES ('E4258866', 'Marlyn Dimmack', 'English Language');
INSERT INTO tutees VALUES ('E4185873', 'Linda Eastridge', 'English Literature');
INSERT INTO tutees VALUES ('E6469338', 'Christalle Bellison', 'Geography');
INSERT INTO tutees VALUES ('E5875444', 'Margot Berzons', 'Global Studies');
INSERT INTO tutees VALUES ('E1243878', 'Alameda Josh', 'History ');
INSERT INTO tutees VALUES ('E1318807', 'Coraline Cerro', 'Japanese Studies');
INSERT INTO tutees VALUES ('E7369409', 'Vanny Odom', 'Malay Studies');
INSERT INTO tutees VALUES ('E3838736', 'Annaliese Antognoni', 'Philosophy');
INSERT INTO tutees VALUES ('E4422219', 'Hilary Waldock', ' Political Science');
INSERT INTO tutees VALUES ('E5861574', 'Keane Muldownie', ' Psychology');
INSERT INTO tutees VALUES ('E4505645', 'Mariska Fraine', ' Social Work');
INSERT INTO tutees VALUES ('E1319433', 'Silvano Gutans', ' Sociology');
INSERT INTO tutees VALUES ('E5686620', 'Liesa Stolli', ' South Asian Studies');
INSERT INTO tutees VALUES ('E5749079', 'Ozzy Remirez', ' Southeast Asian Studies');
INSERT INTO tutees VALUES ('E7627240', 'Massimo Hurrion', 'Theatre Studies');
INSERT INTO tutees VALUES ('E2495628', 'Tobias Jozsa', ' Chemistry');
INSERT INTO tutees VALUES ('E3610385', 'Quinn Lafrentz', 'Data Science and Analytics');
INSERT INTO tutees VALUES ('E1459273', 'Colline Hazeldene', 'Life Sciences');
INSERT INTO tutees VALUES ('E5073942', 'Aldin Buddock', 'Mathematics');
INSERT INTO tutees VALUES ('E2936523', 'Eydie Castangia', 'Physics');
INSERT INTO tutees VALUES ('E9969663', 'Giffer Dungay', 'Quantitative Finance');
INSERT INTO tutees VALUES ('E3940799', 'Giustino Kneale', 'Statistics');
INSERT INTO tutees VALUES ('E6361907', 'Shina Rasch', 'Chinese Language');
INSERT INTO tutees VALUES ('E3670957', 'Julina Rizzo', 'Chinese Studies');
INSERT INTO tutees VALUES ('E5689926', 'Phelia Glamart', ' Communications and New Media');
INSERT INTO tutees VALUES ('E5161428', 'Blinny Harkins', 'Economics');
INSERT INTO tutees VALUES ('E7850625', 'Jorey Creavin', 'English Language');
INSERT INTO tutees VALUES ('E2849243', 'Nonna D''''eathe', 'English Literature');
INSERT INTO tutees VALUES ('E4167383', 'Margette Ben', 'Geography');
INSERT INTO tutees VALUES ('E1338766', 'Dulcea Bowbrick', 'Global Studies');
INSERT INTO tutees VALUES ('E0894230', 'Gino Feehery', 'History ');
INSERT INTO tutees VALUES ('E6630760', 'Miltie Perazzo', 'Japanese Studies');
INSERT INTO tutees VALUES ('E4282397', 'Karleen Titt', 'Malay Studies');
INSERT INTO tutees VALUES ('E6541878', 'Kris Stranaghan', 'Philosophy');
INSERT INTO tutees VALUES ('E3398479', 'Nikolaus Fick', ' Political Science');
INSERT INTO tutees VALUES ('E0771151', 'Iris Rochford', ' Psychology');
INSERT INTO tutees VALUES ('E5564629', 'Brucie Lauritzen', ' Social Work');
INSERT INTO tutees VALUES ('E7889517', 'Glynda Arthur', ' Sociology');
INSERT INTO tutees VALUES ('E3640649', 'Nada Matignon', ' South Asian Studies');
INSERT INTO tutees VALUES ('E3185972', 'Genvieve Getley', ' Southeast Asian Studies');
INSERT INTO tutees VALUES ('E2727084', 'Noam Iiannone', 'Theatre Studies');
INSERT INTO tutees VALUES ('E4462230', 'Tait Maymand', ' Chemistry');
INSERT INTO tutees VALUES ('E2828322', 'Auria Eliaz', 'Data Science and Analytics');
INSERT INTO tutees VALUES ('E6601291', 'Adair Feldman', 'Life Sciences');
INSERT INTO tutees VALUES ('E7082175', 'Fifi Poetz', 'Mathematics');
INSERT INTO tutees VALUES ('E2897357', 'Fulvia Harrisson', 'Physics');
INSERT INTO tutees VALUES ('E0499692', 'Carmine Reddyhoff', 'Quantitative Finance');
INSERT INTO tutees VALUES ('E4679808', 'Kary Vercruysse', 'Statistics');
INSERT INTO tutees VALUES ('E5373246', 'Morgun Smeeton', 'Chinese Language');
INSERT INTO tutees VALUES ('E1649619', 'Georgianna Roggerone', 'Chinese Studies');
INSERT INTO tutees VALUES ('E4057127', 'Alvinia Cristobal', ' Communications and New Media');
INSERT INTO tutees VALUES ('E8103730', 'Wilburt Crichmer', 'Economics');
INSERT INTO tutees VALUES ('E8626097', 'Giraud Battlestone', 'English Language');
INSERT INTO tutees VALUES ('E3512563', 'Aldon Gilbody', 'English Literature');
INSERT INTO tutees VALUES ('E1958649', 'Morgan Ince', 'Geography');
INSERT INTO tutees VALUES ('E5772305', 'Kellie Topley', 'Global Studies');
INSERT INTO tutees VALUES ('E3906755', 'Fraser Camplin', 'History ');
INSERT INTO tutees VALUES ('E8671438', 'Isidro Fullagar', 'Japanese Studies');
INSERT INTO tutees VALUES ('E9050485', 'Fayina Schneider', 'Malay Studies');
INSERT INTO tutees VALUES ('E2121955', 'Dinah Collihole', 'Philosophy');
INSERT INTO tutees VALUES ('E8002781', 'Conchita Jedrychowski', ' Political Science');
INSERT INTO tutees VALUES ('E4791543', 'Meryl Chaim', ' Psychology');
INSERT INTO tutees VALUES ('E1414641', 'Wallache Dragoe', ' Social Work');
INSERT INTO tutees VALUES ('E9933770', 'Elena Camilleri', ' Sociology');
INSERT INTO tutees VALUES ('E1479815', 'Alaric Berthod', ' South Asian Studies');
INSERT INTO tutees VALUES ('E8855528', 'Loella Overil', ' Southeast Asian Studies');
INSERT INTO tutees VALUES ('E2747183', 'Mill Muffen', 'Theatre Studies');
INSERT INTO tutees VALUES ('E8196123', 'Catlin Tarzey', ' Chemistry');
INSERT INTO tutees VALUES ('E3715038', 'Curtice MacConnechie', 'Data Science and Analytics');
INSERT INTO tutees VALUES ('E7453697', 'Irita Spadeck', 'Life Sciences');
INSERT INTO tutees VALUES ('E9709570', 'Smitty Ashard', 'Mathematics');
INSERT INTO tutees VALUES ('E8194232', 'Shalna Siflet', 'Physics');
INSERT INTO tutees VALUES ('E5929431', 'Hermia Belfelt', 'Quantitative Finance');
INSERT INTO tutees VALUES ('E0899200', 'Rollie Garahan', 'Statistics');
INSERT INTO tutees VALUES ('E2250451', 'Laurena Ruggles', 'Chinese Language');
INSERT INTO tutees VALUES ('E0885510', 'Beniamino Karpman', 'Chinese Studies');
INSERT INTO tutees VALUES ('E7429025', 'Branden Fawdrie', ' Communications and New Media');
INSERT INTO tutees VALUES ('E6245664', 'Pooh Toop', 'Economics');
INSERT INTO tutees VALUES ('E8721788', 'Alon Andrelli', 'English Language');
INSERT INTO tutees VALUES ('E6117104', 'Conchita Filintsev', 'English Literature');
INSERT INTO tutees VALUES ('E1729069', 'Sonny Elcoux', 'Geography');
INSERT INTO tutees VALUES ('E7775963', 'Lefty Stote', 'Global Studies');
INSERT INTO tutees VALUES ('E0696733', 'Art Simoneau', 'History ');
INSERT INTO tutees VALUES ('E0843410', 'Fons Gunning', 'Japanese Studies');
INSERT INTO tutees VALUES ('E0244041', 'Margret Antao', 'Malay Studies');
INSERT INTO tutees VALUES ('E4584423', 'Mark Stoffersen', 'Philosophy');
INSERT INTO tutees VALUES ('E3376312', 'Lance McJerrow', ' Political Science');
INSERT INTO tutees VALUES ('E9039600', 'Ivar Nudd', ' Psychology');
INSERT INTO tutees VALUES ('E1559621', 'Sella Taggett', ' Social Work');
INSERT INTO tutees VALUES ('E2039911', 'Patrizio Bettenson', ' Sociology');
INSERT INTO tutees VALUES ('E7060887', 'Karina Krysztofowicz', ' South Asian Studies');
INSERT INTO tutees VALUES ('E6769744', 'Lin Bastable', ' Southeast Asian Studies');
INSERT INTO tutees VALUES ('E6718505', 'Rozalin Loncaster', 'Theatre Studies');
INSERT INTO tutees VALUES ('E9638333', 'Rozele Brastead', ' Chemistry');
INSERT INTO tutees VALUES ('E4851686', 'Lianna Tythacott', 'Data Science and Analytics');
INSERT INTO tutees VALUES ('E2263684', 'Barbabra Clere', 'Life Sciences');
INSERT INTO tutees VALUES ('E1007386', 'Caroljean Stearn', 'Mathematics');
INSERT INTO tutees VALUES ('E4594664', 'Maiga Kinkaid', 'Physics');
INSERT INTO tutees VALUES ('E2841392', 'Sybyl Hurdiss', 'Quantitative Finance');
INSERT INTO tutees VALUES ('E7714521', 'Lane Kelinge', 'Statistics');
INSERT INTO tutees VALUES ('E1060973', 'Gawen Hince', 'Chinese Language');
INSERT INTO tutees VALUES ('E9023104', 'Camilla Oakenfull', 'Chinese Studies');
INSERT INTO tutees VALUES ('E5177889', 'Toby Brookes', ' Communications and New Media');
INSERT INTO tutees VALUES ('E7267891', 'Terrell Errington', 'Economics');
INSERT INTO tutees VALUES ('E0986582', 'Blaine Bonny', 'English Language');
INSERT INTO tutees VALUES ('E4109759', 'Allin Furman', 'English Literature');
INSERT INTO tutees VALUES ('E8572488', 'Huey Bessett', 'Geography');
INSERT INTO tutees VALUES ('E6550837', 'Allene Golde', 'Global Studies');
INSERT INTO tutees VALUES ('E1176713', 'Elliott Comellini', 'History ');
INSERT INTO tutees VALUES ('E2272827', 'Nani Hoggetts', 'Japanese Studies');
INSERT INTO tutees VALUES ('E9653805', 'Elke Salatino', 'Malay Studies');
INSERT INTO tutees VALUES ('E1791065', 'Jesse Vina', 'Philosophy');
INSERT INTO tutees VALUES ('E1655697', 'Dex Manntschke', ' Political Science');
INSERT INTO tutees VALUES ('E8643787', 'Bobbi Coldrick', ' Psychology');
INSERT INTO tutees VALUES ('E4167947', 'Filmer Poetz', ' Social Work');
INSERT INTO tutees VALUES ('E4975863', 'Aksel Fouracre', ' Sociology');
INSERT INTO tutees VALUES ('E8620795', 'Adamo Yankishin', ' South Asian Studies');
INSERT INTO tutees VALUES ('E9166115', 'Nadean Sutherden', ' Southeast Asian Studies');
INSERT INTO tutees VALUES ('E0149855', 'Dillie Christin', 'Theatre Studies');
INSERT INTO tutees VALUES ('E9073551', 'Patricio Karpov', ' Chemistry');
INSERT INTO tutees VALUES ('E4457440', 'Billye Moen', 'Data Science and Analytics');
INSERT INTO tutees VALUES ('E0479752', 'Missy Titcomb', 'Life Sciences');
INSERT INTO tutees VALUES ('E0764479', 'Jarred McGrath', 'Mathematics');
INSERT INTO tutees VALUES ('E6885506', 'Miles Doret', 'Physics');
INSERT INTO tutees VALUES ('E9798095', 'Junette Du Hamel', 'Quantitative Finance');
INSERT INTO tutees VALUES ('E8495433', 'Otis Higginbottam', 'Statistics');
INSERT INTO tutees VALUES ('E7565150', 'Palm Hawley', 'Chinese Language');
INSERT INTO tutees VALUES ('E2424933', 'Denise Ropking', 'Chinese Studies');
INSERT INTO tutees VALUES ('E3974103', 'Boyd Trimme', ' Communications and New Media');
INSERT INTO tutees VALUES ('E5579693', 'Culver Wheeliker', 'Economics');
INSERT INTO tutees VALUES ('E1360296', 'Noami Pococke', 'English Language');
INSERT INTO tutees VALUES ('E9785265', 'Lief Andrault', 'English Literature');
INSERT INTO tutees VALUES ('E2065224', 'Baily Shemmans', 'Geography');
INSERT INTO tutees VALUES ('E2797321', 'Cecelia Nickerson', 'Global Studies');
INSERT INTO tutees VALUES ('E6768142', 'Wilfred Rippon', 'History ');
INSERT INTO tutees VALUES ('E4207880', 'Arlyn Ouver', 'Japanese Studies');
INSERT INTO tutees VALUES ('E1240259', 'Keeley Lafayette', 'Malay Studies');
INSERT INTO tutees VALUES ('E5958291', 'Rinaldo Rehn', 'Philosophy');
